package org.itsnat.droid.impl.browser.serveritsnat;

import android.view.View;

import org.itsnat.droid.EventMonitor;
import org.itsnat.droid.ItsNatDroidException;
import org.itsnat.droid.event.EventStateless;
import org.itsnat.droid.event.UserEvent;
import org.itsnat.droid.impl.browser.PageNotItsNatImpl;

/**
 * Created by jmarranz on 23/12/2015.
 */
public class ItsNatDocNotItsNatImpl extends ItsNatDocImpl
{
    public ItsNatDocNotItsNatImpl(PageNotItsNatImpl page,int errorMode)
    {
        super(page,errorMode);
    }

    @Override
    public void addEventMonitor(EventMonitor monitor)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public boolean removeEventMonitor(EventMonitor monitor)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public void setEnableEventMonitors(boolean value)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public UserEvent createUserEvent(String name)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public void dispatchUserEvent(View currTargetView,UserEvent evt)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public void fireUserEvent(View currTargetView,String name)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public EventStateless createEventStateless()
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }

    @Override
    public void dispatchEventStateless(EventStateless evt,int commMode,long timeout)
    {
        throw new ItsNatDroidException("This method only can be called when the page was generated by a ItsNat Server servlet");
    }


}
